# Generated by Django 4.1 on 2022-11-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishikhojapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='farmer_addr',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='farmer_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='farmer',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmer',
            name='registration_no',
            field=models.IntegerField(default=0),
        ),
    ]
