# Generated by Django 4.1 on 2022-11-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishikhojapp', '0002_rename_farmer_addr_farmer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
