# Generated by Django 4.1 on 2022-11-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishikhojapp', '0003_farmer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractor',
            name='tractor_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
