# Generated by Django 4.1 on 2022-11-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishikhojapp', '0004_alter_tractor_tractor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='contact_no',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
